name: Verification Pipeline
on:
  pull_request:
    branches: [ develop, main ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Output Status Indicator
        run: echo 'CI running'
